name: update pkgbuild

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      if_updated: ${{ steps.tg-update.outputs.if_updated }}

    steps:
      - uses: actions/checkout@v4

      - name: Update PKGBUILD
        id: tg-update
        run: |
          ./pkgver-update.sh
          if_updated=$(cat updated)
          newver=$(cat newver)
          echo "if_updated=$if_updated"
          echo "if_updated=$if_updated" >> "$GITHUB_OUTPUT"
          echo "newver=$newver"
          echo "newver=$newver" >> "$GITHUB_OUTPUT"

      - name: Commit and Push Changes
        if: steps.tg-update.outputs.if_updated == 1
        run: |
          git add -v pkgbuilds
          git config --global user.name Sakari
          git config --global user.email 20642596+sakarie9@users.noreply.github.com
          git commit -m "Update to ${{ steps.tg-update.outputs.newver }}"
          git push

  build:
    uses: ./.github/workflows/build-pkgbuild.yaml
    needs: update
    if: needs.update.outputs.if_updated == 1
    secrets: inherit
